In [12]:
import requests
import pandas as pd

headers = {'User-Agent': "email@address.com"}

# get all companies data
companyTickers = requests.get(
    "https://www.sec.gov/files/company_tickers.json",
    headers=headers
    )

# review response / keys
# print(companyTickers.json().keys())

# format response to dictionary and get first key/value
firstEntry = companyTickers.json()['0']

# parse CIK // without leading zeros
directCik = companyTickers.json()['0']['cik_str']

# dictionary to dataframe
companyData = pd.DataFrame.from_dict(companyTickers.json(),
                                     orient='index')

# add leading zeros to CIK
companyData['cik_str'] = companyData['cik_str'].astype(
                           str).str.zfill(10)

# review data
print(companyData[:10])

cik = companyData[0:1]['cik_str'].iloc[0]

# get company specific filing metadata
filingMetadata = requests.get(
    f'https://data.sec.gov/submissions/CIK{cik}.json',
    headers=headers
    )

# review json 
print(filingMetadata.json().keys())
filingMetadata.json()['filings']
filingMetadata.json()['filings'].keys()
filingMetadata.json()['filings']['recent']
filingMetadata.json()['filings']['recent'].keys()

# dictionary to dataframe
allForms = pd.DataFrame.from_dict(
             filingMetadata.json()['filings']['recent']
             )

# review columns
allForms.columns
allForms[['accessionNumber', 'reportDate', 'form']].head(50)

      cik_str ticker                                      title
0  0000320193   AAPL                                 Apple Inc.
1  0001045810   NVDA                                NVIDIA CORP
2  0000789019   MSFT                             MICROSOFT CORP
3  0001652044  GOOGL                              Alphabet Inc.
4  0001018724   AMZN                             AMAZON COM INC
5  0001326801   META                       Meta Platforms, Inc.
6  0001046179    TSM  TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD
7  0001067983  BRK-B                     BERKSHIRE HATHAWAY INC
8  0001318605   TSLA                                Tesla, Inc.
9  0000059478    LLY                             ELI LILLY & Co
dict_keys(['cik', 'entityType', 'sic', 'sicDescription', 'ownerOrg', 'insiderTransactionForOwnerExists', 'insiderTransactionForIssuerExists', 'name', 'tickers', 'exchanges', 'ein', 'description', 'website', 'investorWebsite', 'category', 'fiscalYearEnd', 'stateOfIncorporation', 'stateOfIncorporationDescription', 'addresses', 'phone', 'flags', 'formerNames', 'filings'])

         accessionNumber  reportDate     form
0   0001140361-24-044880               S-3ASR
1   0000320193-24-000123  2024-09-28     10-K
2   0000320193-24-000120  2024-10-31      8-K
3   0000320193-24-000116  2024-10-15        4
4   0000320193-24-000114  2024-10-04        4
5   0001958244-24-005135                  144
6   0000320193-24-000112  2024-10-01        4
7   0000320193-24-000111  2024-10-01        4
8   0000320193-24-000110  2024-10-01        4
9   0000320193-24-000109  2024-10-01        4
10  0000320193-24-000108  2024-10-01        4
11  0001950047-24-007542                  144
12  0001973141-24-000479                  144
13  0001959173-24-006827                  144
14  0001973141-24-000478                  144
15  0000320193-24-000102  2024-09-28        5
16  0000320193-24-000101  2024-09-29        4
17  0000320193-24-000100  2024-09-29        4
18  0000320193-24-000099  2024-09-29        4
19  0000320193-24-000098  2024-09-29        4
20  0000320193-24-000097  2024-09-29        4
21  0000320193-24-000096  2024-09-29        4
22  0001140361-24-040659  2024-09-10      8-K
23  0001140361-24-038601  2024-08-26      8-K
24  0001140361-24-038403  2024-08-20      8-K
25  0000320193-24-000088  2024-08-15        4
26  0000320193-24-000086  2024-08-09        4
27  0000320193-24-000084  2024-08-05        4
28  0001950047-24-005824                  144
29  0000320193-24-000081  2024-06-29     10-Q
30  0000320193-24-000080  2024-08-01      8-K
31  0000320193-24-000075  2024-05-30        4
32  0001921094-24-000702                  144
33  0000320193-24-000073  2024-05-15        4
34  0000000000-24-005673               UPLOAD
35  0000320193-24-000071  2024-05-10        4
36  0001140361-24-024352  2024-05-03      8-K
37  0000320193-24-000069  2024-03-30     10-Q
38  0000320193-24-000067  2024-05-02      8-K
39  0000320193-24-000061              CORRESP
40  0000320193-24-000058  2024-04-15        4
41  0000320193-24-000056  2024-04-11        4
42  0000320193-24-000055  2024-04-11        4
43  0001958244-24-001666                  144
44  0001973141-24-000220                  144
45  0001140361-24-018378              CORRESP
46  0000320193-24-000052  2024-04-01        4
47  0000320193-24-000051  2024-04-01        4
48  0000320193-24-000050  2024-04-01        4
49  0000320193-24-000049  2024-04-01        4

In [42]:
# get company facts data
companyFacts = requests.get(
    f'https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json',
    headers=headers
    )

# #review data
companyFacts.json().keys()
companyFacts.json()['facts']
companyFacts.json()['facts'].keys()

# filing metadata
companyFacts.json()['facts']['dei'][
    'EntityCommonStockSharesOutstanding']
companyFacts.json()['facts']['dei'][
    'EntityCommonStockSharesOutstanding'].keys()
companyFacts.json()['facts']['dei'][
    'EntityCommonStockSharesOutstanding']['units']
companyFacts.json()['facts']['dei'][
    'EntityCommonStockSharesOutstanding']['units']['shares']
companyFacts.json()['facts']['dei'][
    'EntityCommonStockSharesOutstanding']['units']['shares'][0]

# concept data // financial statement line items
companyFacts.json()['facts']['us-gaap']
df = pd.DataFrame.from_dict(companyFacts.json()['facts']['us-gaap'])
df.columns

# # different amounts of data available per concept
# companyFacts.json()['facts']['us-gaap']['AccountsPayable']
# companyFacts.json()['facts']['us-gaap']['Revenues']
# companyFacts.json()['facts']['us-gaap']['Assets']

# # get company concept data
# companyConcept = requests.get(
#     (
#     f'https://data.sec.gov/api/xbrl/companyconcept/CIK{cik}'
#      f'/us-gaap/Assets.json'
#     ),
#     headers=headers
#     )

# # review data
# companyConcept.json().keys()
# companyConcept.json()['units']
# companyConcept.json()['units'].keys()
# companyConcept.json()['units']['USD']
# companyConcept.json()['units']['USD'][0]

# # parse assets from single filing
# companyConcept.json()['units']['USD'][0]['val']

# # get all filings data 
# assetsData = pd.DataFrame.from_dict((
#                companyConcept.json()['units']['USD']))

# # review data
# assetsData.columns
# assetsData['form']

# # get assets from 10Q forms and reset index
# assets10Q = assetsData[assetsData['form'] == '10-Q']
# assets10Q = assets10Q.reset_index(drop=True)

# # # plot 
# assets10Q.plot(x='end', y='val')